name: Notify

on:
  schedule:
    - cron: '0 0,2,10,12,14,16,18,20,22 * * 1-5'
  workflow_dispatch:

jobs:
  notify_schedule:
    env:
      ORG: ${{ github.repository_owner }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify PRs Summary
        uses: octokit/graphql-action@v2.x
        id: prs_summary
        with:
          query: |
            query allPRCounts(
              $reviewQuery: String!,
              $feedbackQuery: String!,
              $approvalQuery: String!
            ) {
              needReview: search(type: ISSUE, query: $reviewQuery, last: 100) {
                issueCount
              }
              withFeedback: search(type: ISSUE, query: $feedbackQuery, last: 100) {
                issueCount
              }
              withApproval: search(type: ISSUE, query: $approvalQuery, last: 100) {
                issueCount
              }
            }
          variables: |
            reviewQuery: "org:${{env.ORG}} repo:vdo-devel state:open is:pr -label:\"on hold\" draft:false review:required"
            feedbackQuery: "org:${{env.ORG}} repo:vdo-devel state:open is:pr -label:\"on hold\" draft:false review:changes_requested"
            approvalQuery: "org:${{env.ORG}} repo:vdo-devel state:open is:pr -label:\"on hold\" draft:false review:approved"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: slackapi/slack-github-action@v1.24.0
        if: ${{ env.REVIEW_COUNT > 0 || env.REPLY_COUNT > 0 || env.APPROVE_COUNT > 0 }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "PR_MSG_REVIEWS": "${{env.REVIEW_COUNT}} PRs requesting a review",
              "PR_MSG_REPLIES": "${{env.REPLY_COUNT}} PRs with review feedback",
              "PR_MSG_APPROVALS": "${{env.APPROVE_COUNT}} PRs with review approval",              
              "PR_LINK_REVIEWS": "github.com/search?q=org%3A${{env.ORG}}+type%3Apr+is%3Aopen+-label%3A%22on%20hold%22+draft%3Afalse+review%3Arequired+&type=pullrequests",
              "PR_LINK_REPLIES": "github.com/search?q=org%3A${{env.ORG}}+type%3Apr+is%3Aopen+-label%3A%22on%20hold%22+draft%3Afalse+review%3Achanges_requested+&type=pullrequests",
              "PR_LINK_APPROVALS": "github.com/search?q=org%3A${{env.ORG}}+type%3Apr+is%3Aopen+-label%3A%22on%20hold%22+draft%3Afalse+review%3Aapproved+&type=pullrequests"             
            }
        env:
          REVIEW_COUNT: ${{ fromJSON(steps.prs_summary.outputs.data).needReview.search.issueCount }}
          REPLY_COUNT: ${{ fromJSON(steps.prs_summary.outputs.data).withFeedback.search.issueCount }}
          APPROVE_COUNT: ${{ fromJSON(steps.prs_summary.outputs.data).withApproval.search.issueCount }}         
          SLACK_WEBHOOK_URL: ${{ secrets.SLACKMSG_TEST }}
