name: PR Assigner

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review, synchronize ]
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Assign:
    runs-on: ubuntu-latest
    steps:
      # Run assignment action
      - name: Assign reviewers and assignees
        uses: dm-vdo/vdo-auto-assign@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
